
# whitelist
branches:
  only:
    - master
    - staging
    - production
services:
#Enable docker service inside travis
  - docker
script:
  #build the image
  - bash config/buildDockerImage.sh
notifications:
  slack: 3blades:2UxzPYWeoYbj80mCt5MdYeez
env:
  - $DOCKER_IMAGE_NAME="3blades/openresty"
