
# whitelist
branches:  
  only:
    - master
    - staging
    - production
services:  
#Enable docker service inside travis
  - docker
before_install:  
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script: 
  #build the image
  - docker build --no-cache -t $DOCKER_IMAGE_NAME .
  #tag image
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:build-$TRAVIS_BUILD_NUMBER
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest
  #push image
  - docker push $DOCKER_IMAGE_NAME:build-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_IMAGE_NAME:latest
notifications:
  slack: 3blades:0lcWo2AurVy41XkVdyFVejCG
env:
  - $DOCKER_IMAGE_NAME="3blades/openresty"
